services:
  nginx:
    container_name: nginx-dns
    image: nginx:latest
    networks:
      dns:
        ipv4_address: 172.30.0.2
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: ${TZ}
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
    volumes:
      - './src/nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - pihole
      - unbound
    restart: unless-stopped

  pihole:
    container_name: pihole-dns
    image: pihole/pihole:latest
    hostname: ${PIHOLE_HOSTNAME}
    networks:
      dns:
        ipv4_address: 172.30.0.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      DNS1: '172.30.0.4'
      DNS2: 'none'
    volumes:
      - './src/pihole/persist/pihole:/etc/pihole'
      - './src/pihole/persist/dnsmasq.d:/etc/dnsmasq.d'
      - './src/pihole/persist/logs:/var/log'
    depends_on:
      - unbound
    restart: unless-stopped
  
  unbound:
      container_name: unbound-dns
      image: "mvance/unbound-rpi:latest"
      networks:
        dns:
          ipv4_address: 172.30.0.4
      ports:
        - "53:53/tcp"
        - "53:53/udp"
      environment:
        TZ: ${TZ}
        WEBPASSWORD: ${UNBOUND_WEBPASSWORD}
      volumes:
        - "./src/unbound:/opt/unbound/etc/unbound"
      restart: unless-stopped

networks:
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24